<div class="container">
	<?php
		$this->title = "Deletar Album";
		$this->headTitle($this->title);
	?>
	<p>Tem certeza que quer deletar?
	'<?php echo $this->escape($this->album['title']); ?>' de
	'<?php echo $this->escape($this->album['artist']); ?>'?
	</p>
	<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
		<div>
		<input type="hidden" name="id" value="<?php echo $this->album['id']; ?>" />
		<input type="submit" name="del" value="Yes"/>
		<input type="submit" name="del" value="No"/>
		</div>
	</form>
</div>